//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UyeForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyeDb
    {
        public int id { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string kadi { get; set; }
        public string sifre { get; set; }
        public string telefon { get; set; }
        public string mail { get; set; }
        public string adres { get; set; }
        public string il { get; set; }
        public string sdurum { get; set; }
        public Nullable<System.DateTime> dtarihi { get; set; }
        public string uyeliktipi { get; set; }
        public string boy { get; set; }
        public string kilo { get; set; }
        public string fotograf { get; set; }
    }
}
